### ISSUE TITLE
Provide a way to use material-css without a menu

### ISSUE THREAD

**Issue by apollo13** [imperdiblesoft/material-css#1]
Currently, mc-layout="front" goes a long way already, but one cannot use it in conjunction with a header:
```
<!DOCTYPE html>
<html>
<head>
  <link href="material-css.css" type="text/css" rel="stylesheet"/>
  <link href="color-themes/android-theme.css" type="text/css" rel="stylesheet"/>
  <script src="material-css.js" type="text/javascript"></script>
</head>
<body mc-layout="front">
  <header class="mc-header">
    <div class="mc-header-line">
      <div class="mc-title">HI</div>
    </div>
  </header>
  <div class="mc-content">
    <h1 class="mc-title">Welcome to blabla</h1>
    <p class="mc-text">This is some test text</p>
  </div>
</body>
</html>
```
It would be nice if I could write pages without a menu, or even better provide a way for a menu like seen on http://inbox.google.com/

**Comment by imperdiblesoft** [comment]
Implemented mc-layout="hidden-nav" and mc-layout="no-nav" :)

**Comment by apollo13** [comment]
Nice, thank you!

**Comment by imperdiblesoft** [comment]
I didn't see your post on ImperdibleSoft's forum until now!! I already answered you, and I'll be attentive for your answers.
