### ISSUE TITLE
Icon Fonts Not Being Served

### ISSUE THREAD

**Issue by bretonio** [ImperdibleSoft/material-css#5]
I have set up your framework in Roots and Express and Harp and using both the CDN and linking to `npm i materialcss`  ... I decide to start out with a header element and the Material Icons &mdash; served from Google Fonts &mdash; do not render, although my select header and body fonts do.

My _`layout.jade` ...

```
doctype
html
	head
		link(rel="stylesheet" href="/main.css")
		script(src='node_modules/materialcss/material-css/material-css.js')

		title Alteregoistic Material

		link(rel='stylesheet', href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css')
        
		link(rel='stylesheet', href='https://fonts.googleapis.com/css?family=Josefin Slab |Quicksand|Material+Icons')

		style.
			body, html {
				font-family: 'Quicksand', sans-serif;
			}
			h1, h2, h3, h4, h5, h6 {
				font-family: 'Josefin Slab', sans-serif;
				font-weight: 300;
	body
		!= yield

```

And my `index.jade` so far ...

```
header.mc-header
	.mc-header-line
		span.mc-button-icon(mc-action='menu')
		p.mc-title Engenho Novo LLC
		.mc-right
			span.mc-button-icon(mc-action='download')
			span.mc-button-icon(mc-action='share')
			span.mc-button-icon(mc-action='autorenew')
```

Too lazy so far to set  up icons using `npm i material-design-icons`  ... I will let you know ...

**Comment by lordfido** [comment]
Hi @bretonio, is it possible that you forgot to load `node_modules/materialcss/material-css/material-css.css`? I cannot see any reference to the CSS file

**Comment by bretonio** [comment]
It was not that! I was duly hooked into your CDN. Looks like your icon set is a but a subset of the Material set, so I can use any icon I want linking to Google Fonts and using the correct syntax. `i.material-icons favorite` or `i.fa.fa-heart.fa-lg Material-CSS.` 

Case closed.

I actually dropped by on another errand. 

Modals (dialogs). 

How to trigger with button or some example code?

thx cb

**Comment by lordfido** [comment]
Hi @bretonio!
For sure I didn't downloaded all icons! I should have thought that was the problem...

Anyways I'll close the issue.

Regarding to modals (dialogs) here I link you 2 resources:
*[Modal examples](http://material-css.com/#/dialogs)
*[MC-trics (dialogs)](http://material-css.com/#/tricks?toogle-dialogs)
